Repository ocsigen/ts2ocaml, pull requests merged in 2021-11, with the labels that each got.

#31 Replace run action with copy in the document
  docs/js_of_ocaml.md
Labels: documentation

#35 Add better heuristic for relative imports
  build.fsx
  docs/development.md
  src/Extensions.fs
  src/JsHelper.fs
  src/Main.fs
  src/Naming.fs
  src/Syntax.fs
  src/Target.fs
  src/Targets/JsOfOCaml/OCamlHelper.fs
  src/Targets/JsOfOCaml/Target.fs
  src/Targets/JsOfOCaml/Writer.fs
  src/Targets/ParserTest.fs
  src/ts2ocaml.fsproj
  webpack.config.js
Labels: bug, enhancement, doc-needed

#37 Follow relative references
  CHANGELOG.md
  build.fsx
  docs/common_options.md
  package.json
  src/Common.fs
  src/Extensions.fs
  src/JsHelper.fs
  src/Main.fs
  src/Parser.fs
  src/Targets/JsOfOCaml/Common.fs
  src/Targets/JsOfOCaml/Target.fs
  src/Targets/JsOfOCaml/Writer.fs
  test/jsoo/src/dune
  yarn.lock
Labels: enhancement
